import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    home: [
      {
        id: 0,
        name: "Bendahara",
        slug: "bendahara",
        image: "/post/post.jpg",
        tools: ["vscode", "php", "mysql"],
        year: 2019,
        platform: "ui",
        desc: "Bendahara",
      },
      {
        id: 1,
        name: "Projectsekolah!",
        slug: "projectsekolah",
        image: "/post/psekolah.jpg",
        tools: ["vscode", "php", "mysql"],
        year: 2019,
        platform: "web",
        desc:
          "Aplikasi ini digunakan untuk mengabsen piket dikelas karena saya ditunjuk untuk menjadi ketua piket. Aplikasi ini juga digunakan untuk melihat jadwal pelajaran disekolah. Aplikasi ini dibuat dengan php native, mysql dan css native tanpa framework karena ini adalah project pertama saya",
      },
      {
        id: 2,
        name: "bankmini",
        slug: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
      {
        id: 2,
        name: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
      {
        id: 2,
        name: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
      {
        id: 2,
        name: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
      {
        id: 2,
        name: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
      {
        id: 2,
        name: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
      {
        id: 2,
        name: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
    ],
    works: [
      {
        id: 0,
        name: "Bendahara",
        slug: "bendahara",
        image: "/post/post.jpg",
        tools: ["vscode", "php", "mysql"],
        year: 2019,
        platform: "ui",
        desc: "Bendahara",
      },
      {
        id: 1,
        name: "Projectsekolah!",
        slug: "projectsekolah",
        image: "/post/psekolah.jpg",
        tools: ["vscode", "php", "mysql"],
        year: 2019,
        platform: "web",
        desc:
          "Aplikasi ini digunakan untuk mengabsen piket dikelas karena saya ditunjuk untuk menjadi ketua piket. Aplikasi ini juga digunakan untuk melihat jadwal pelajaran disekolah. Aplikasi ini dibuat dengan php native, mysql dan css native tanpa framework karena ini adalah project pertama saya",
      },
      {
        id: 2,
        name: "bankmini",
        slug: "bankmini",
        image: "/post/bankmini.png",
        tools: ["vscode", "php", "mysql"],
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
      {
        id: 3,
        name: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
      {
        id: 4,
        name: "bankmini",
        image: "/post/bankmini.png",
        year: 2019,
        platform: "web",
        desc: "Bankmini",
      },
    ],
    selectedCategory: "All",
  },
  mutations: {},
  actions: {},
  modules: {},
});
